[package]
name = "insertion-set"
description = "Performs a set of batched insertions on a vector"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Techcable/insertion-set.rust"

